Update model value when switch is disabled
frapontillo/angular-bootstrap-switch pull request #133
Opened 2017-12-01 06:53 UTC by aprilssmile

Workaround for https://github.com/Bttstrp/bootstrap-switch/issues/540

For a year owner does not fix the problem of updating model value when the switch is disabled and even open pull request did not help. But this functional is important so I added workround that will not break anything if this problem will be fixed in linked module. But when will this happen? It seems that this repository is no longer being active supported.

2017-12-01 10:09 UTC, frapontillo requested changes
Thanks for the PR. Can you please also add a live plunker which shows the new behaviour?

2017-12-01 10:09 UTC, frapontillo commented on test/spec/directives/bsSwitchSpec.js
> +  function makeTestChangeModelWhenSwitchIsDeactivated() {
Can you please properly reformat this code?

2017-12-01 10:47 UTC, aprilssmile commented
Code reformatted.
Plunk: http://embed.plnkr.co/k93mJV0cIzqAeJtlO0J3/

2017-12-01 11:09 UTC, aprilssmile commented
Finished

2017-12-01 11:42 UTC, frapontillo reviewed
Awesome PR! Thanks for the effort!

2017-12-01 11:42 UTC, frapontillo approved these changes

2017-12-01 11:42 UTC, merged

2017-12-01 11:46 UTC, aprilssmile commented
Thank you for fast feedback :)

2018-05-28 04:31 UTC, dacsy commented
Hi @frapontillo 
Seems we haven't release this fixed since 6 months now.
Can I expect a release of this fixed soon ?
Thank you